program: train.py
command:
  - ${env}
  - python
  - ${program}
  - "finetune"
  - ${args}
  - "--finetune_rf"
method: grid
metric:
  name: "Test/Accuracy"
  goal: maximize
parameters:
  learning_rate: 
    value: 5e-3
  optimizer:
    value: "adam"
  model_name:
    value: "elmo_single_sentence"
  dataset_name:
    values: ["rotten_tomatoes", "sst2"]
  epochs:
    value: 20
  batch_size:
    value: 64
  logs_per_epoch:
    value: 1
  epochs_per_model_save:
    value: 100
  model_weights:
    values: ['models/retrofit_elmo_2022-03-08-1011/save_epoch_0.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_1.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_2.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_3.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_4.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_5.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_6.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_7.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_8.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_9.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_10.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_11.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_12.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_13.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_14.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_15.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_16.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_17.pth', 'models/retrofit_elmo_2022-03-08-1011/save_epoch_18.pth']
