program: train.py
command:
  - ${env}
  - python
  - ${program}
  - "finetune"
  - ${args}
  - "--finetune_rf"
method: grid
metric:
  name: "Test/Accuracy"
  goal: maximize
parameters:
  learning_rate: 
    value: 5e-3
  optimizer:
    value: "adam"
  model_name:
    value: "elmo_single_sentence"
  ft_dataset_name:
    values: ["rotten_tomatoes", "sst2"]
  epochs:
    value: 20
  batch_size:
    value: 64
  logs_per_epoch:
    value: 1
  epochs_per_model_save:
    value: 100
  model_weights:
    values: ['models/retrofit_elmo_2022-03-10-1727/save_step_68.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_137.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_206.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_275.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_344.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_413.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_482.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_551.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_620.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_689.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_758.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_827.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_896.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_965.pth', 'models/retrofit_elmo_2022-03-10-1727/save_step_1034.pth']
